In [2]:
import pandas as pd

df_BBC = pd.read_csv('BBC_raw.csv', sep=';')
len(df_BBC)

3803

In [3]:
df_BBC = df_BBC.drop_duplicates(subset = ['title'])
df_BBC.dropna(subset = ["synops_long"], inplace = True)
df_BBC = df_BBC.reset_index()
len(df_BBC)

1895

In [17]:
df_BBC.head()

index  id                        title  \
0      0   0                    BBC Proms   
1      1   1                         Port   
2      3   3  Ceiliúradh na Féile Pádraig   
3      4   4              Songs of Praise   
4      5   5      Radio 1's Out Out! Live   

                                         description  \
0  Australian tenor Stuart Skelton is joined by L...   
1  Previously unseen music from the series Port, ...   
2  John Toal and Pauline Scanlon introduce an eve...   
3  Claire McCollum explores Edinburgh and shares ...   
4  Music’s biggest names celebrate the return of ...   

                                               image  \
0  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
1  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
2  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
3  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
4  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   

                                            keywords  \
0  BBC, iPlayer, TV, BBC Proms, 2021: Last Night ...   
1        BBC, iPlayer, TV, Port, Series 5: Episode 4   
2      BBC, iPlayer, TV, Ceiliúradh na Féile Pádraig   
3       BBC, iPlayer, TV, Songs of Praise, Edinburgh   
4  BBC, iPlayer, TV, Radio 1s Out Out! Live, Best...   

                                      synopses_small  \
0  Australian tenor Stuart Skelton is joined by L...   
1  Previously unseen music from the series Port, ...   
2  John Toal and Pauline Scanlon introduce an eve...   
3  Claire McCollum explores Edinburgh and shares ...   
4  Music’s biggest names celebrate the return of ...   

                                          synops_med  \
0  Australian tenor Stuart Skelton is joined by L...   
1  Julie Fowlis a’ lìbhrigeadh ceòl bhon t-sreath...   
2  John Toal and Pauline Scanlon introduce an eve...   
3  Claire McCollum goes on a Christian heritage t...   
4  BBC Radio 1 host a star-studded party from Wem...   

                                         synops_long category  \
0  Katie Derham hosts continued live coverage fro...    Music   
1  Bidh Druthag Bheag Eile a’ tarraing ri chèile ...    Music   
2  John Toal and Pauline Scanlon introduce an eve...    Music   
3  Claire McCollum explores Edinburgh and discove...    Music   
4  BBC Radio 1 host a star-studded party from Wem...    Music   

                            channel language         release_date  \
0                   bbc_radio_three    False      9pm 11 Sep 2021   
1                          bbc_alba    False           9 Jul 2020   
2  bbc_two_northern_ireland_digital    False          17 Mar 2017   
3                           bbc_one    False   1:15pm 20 Feb 2022   
4                     bbc_radio_one    False  11:30pm 17 Oct 2021   

   duration_sec  topic  
0          5247  music  
1          1037  music  
2          3538  music  
3          2044  music  
4          3423  music

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Initialize an instance of tf-idf Vectorizer
tfidf_vectorizer = TfidfVectorizer()
corpus = df_BBC.synops_long

# Generate the tf-idf vectors for the corpus
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# compute and print the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix).round(2)
print(cosine_sim)

[[1.   0.02 0.03 ... 0.08 0.01 0.06]
 [0.02 1.   0.08 ... 0.02 0.08 0.03]
 [0.03 0.08 1.   ... 0.03 0.14 0.02]
 ...
 [0.08 0.02 0.03 ... 1.   0.01 0.08]
 [0.01 0.08 0.14 ... 0.01 1.   0.02]
 [0.06 0.03 0.02 ... 0.08 0.02 1.  ]]


In [19]:
cosine_sim.shape

(1895, 1895)

In [20]:
import numpy as np
np.min(cosine_sim)
np.max(cosine_sim)
#np.max(cosine_sim, axis = 0)

1.0

In [48]:
indices = pd.Series(df_BBC.index, index = df_BBC['title']).drop_duplicates()

def get_recommendations(title, cosine, indices):
    # Get the index of the movie that matches the title
    idx = indices[title]
    # Get the pairwsie similarity scores
    sim_scores = list(enumerate(cosine[idx]))
    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse = True)
    # Get the scores for 10 most similar movies
    sim_scores = sim_scores[0:9]
    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]
    # Return the top 10 most similar movies
    return df_BBC['title'].iloc[movie_indices]

In [49]:
tfidf = TfidfVectorizer(stop_words = 'english')
# Construct the TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
# Generate the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
# Generate recommendations
print(get_recommendations("Planet Earth II", cosine_sim, indices))

312                     Planet Earth II
338                     The Mating Game
382             Wales: Land of the Wild
360            Earth’s Tropical Islands
311    Chris Packham's Animal Einsteins
358            Seven Worlds, One Planet
410                Animals with Cameras
294                    Earth from Space
418                           Zoo Quest
Name: title, dtype: object


In [50]:
alpha = 0.2
selection = get_recommendations("Planet Earth II", cosine_sim, indices).index.values
RelDiversity = (1-cosine_sim[list(selection)]).mean(axis = 0).round(2)
quality = (1 - alpha) * cosine_sim + alpha * RelDiversity
print(get_recommendations("Planet Earth II", quality, indices))

312                 Planet Earth II
382         Wales: Land of the Wild
963                 Worzel Gummidge
1760         World's Busiest Cities
429                 Born to Be Wild
338                 The Mating Game
99      Planet Earth: A Celebration
344                   Animal Babies
432               The Wild Gardener
Name: title, dtype: object


In [51]:
print(df_BBC['image'].iloc[0].format(recipe = "288x162"))

https://ichef.bbci.co.uk/images/ic/288x162/p09w0p59.jpg


In [54]:
list(get_recommendations("Planet Earth II", cosine_sim, indices).index)

[312, 338, 382, 360, 311, 358, 410, 294, 418]

In [164]:
ind = list(get_recommendations("Planet Earth II", cosine_sim, indices).index)
df_BBC.filter(items = ind, axis=0)

index   id                             title  \
312    365  365                   Planet Earth II   
338    391  391                   The Mating Game   
360    414  414          Earth’s Tropical Islands   
382    437  437           Wales: Land of the Wild   
311    364  364  Chris Packham's Animal Einsteins   
294    346  346                  Earth from Space   
358    412  412          Seven Worlds, One Planet   
410    469  469              Animals with Cameras   
99     117  117       Planet Earth: A Celebration   

                                           description  \
312  Cities can be worlds of surprising opportunity...   
338  Animals facing the greatest odds have the most...   
360  Exploring Hawaii, a tropical sanctuary for any...   
382  An epic journey following Wales’s rivers, disc...   
311  Chris discovers the cleverest animal traveller...   
294  Cameras in space show Earth changing rapidly. ...   
358      The most spectacular moments from the series.   
410  State-of-the-art cameras offer a fresh look on...   
99   Escape with Sir David Attenborough to the wild...   

                                                 image  \
312  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
338  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
360  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
382  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
311  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
294  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
358  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
410  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
99   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   

                                              keywords  \
312       BBC, iPlayer, TV, Planet Earth II, 6. Cities   
338  BBC, iPlayer, TV, The Mating Game, Series 1: 5...   
360  BBC, iPlayer, TV, Earth’s Tropical Islands, Se...   
382  BBC, iPlayer, TV, Wales: Land of the Wild, Sec...   
311  BBC, iPlayer, TV, Chris Packhams Animal Einste...   
294  BBC, iPlayer, TV, Earth from Space, Series 1: ...   
358  BBC, iPlayer, TV, Seven Worlds, One Planet, Co...   
410  BBC, iPlayer, TV, Animals with Cameras, Series...   
99       BBC, iPlayer, TV, Planet Earth: A Celebration   

                                        synopses_small  \
312  Cities can be worlds of surprising opportunity...   
338  Animals facing the greatest odds have the most...   
360  Exploring Hawaii, a tropical sanctuary for any...   
382  An epic journey following Wales’s rivers, disc...   
311  Chris discovers the cleverest animal traveller...   
294  Cameras in space show Earth changing rapidly. ...   
358      The most spectacular moments from the series.   
410  State-of-the-art cameras offer a fresh look on...   
99   Escape with Sir David Attenborough to the wild...   

                                            synops_med  \
312  Cities can be worlds of surprising opportunity...   
338  All life is driven by the need to breed. Yet f...   
360  Exploring Hawaii, a tropical sanctuary for any...   
382  An epic journey following Wales’s rivers from ...   
311  Chris discovers the cleverest animal traveller...   
294  Cameras in space show that Earth is changing r...   
358  The most spectacular moments from the series, ...   
410  Wildlife cameraman Gordon Buchanan leads a tea...   
99   Escape with Sir David Attenborough to the worl...   

                                           synops_long          category  \
312  Cities are growing at a faster rate than any o...            Nature   
338  One basic need connects all life on earth - th...            Nature   
360  This is a journey across Hawaii’s varied islan...            Nature   
382  An epic journey following Wales’s rivers from ...       Documentary   
311  Chris Packham discovers the clever methods tha...            Nature   
294  Cameras in space tell stories of life on our p...  Science & Nature   
358  The most spectacular moments fro

In [ ]:
with open('similarity.npy', 'wb') as f:
    np.save(f, cosine_sim)

In [ ]:
with open('similarity.npy', 'rb') as f:
    simsim = np.load(f)

In [89]:
set(df_BBC.category)
df_BBC[df_BBC.category.isin(["Arts", "Beauty"])]

index    id                                           title  \
75       91    91                      Anything Goes: The Musical   
177     204   204                     Dance: BBC Introducing Arts   
178     205   205  Truman and Tennessee: An Intimate Conversation   
183     211   211                                            Ex-S   
187     215   215                                Big Book Weekend   
...     ...   ...                                             ...   
292     344   344                                  Dancing Nation   
790     960   960            Glow Up: Britain's Next Make-Up Star   
1457   2317  2317                                         Tonight   
1517   2480  2480                 John Buchan: Master of Suspense   
1565   2637  2637                                         Profile   

                                            description  \
75    A major new production of the classic musical ...   
177   Brenda Emmanus presents short films that combi...   
178   Docudrama that creates a fascinating compariso...   
183   Jasper Conran designs the costumes for Swan La...   
187   Alex Clark talks to the queen of crime Val McD...   
...                                                 ...   
292   Highlights of world-class performances by the ...   
790   The Glow Up final. An industry masterclass and...   
1457  The writer Dame Rebecca West in conversation w...   
1517  Docudrama about the life of author John Buchan...   
1565  Philip Pullman explores Oxford, where he was a...   

                                                  image  \
75    https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
177   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
178   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
183   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
187   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
...                                                 ...   
292   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
790   https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
1457  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
1517  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   
1565  https://ichef.bbci.co.uk/images/ic/{recipe}/p0...   

                                               keywords  \
75         BBC, iPlayer, TV, Anything Goes: The Musical   
177       BBC, iPlayer, TV, Dance: BBC Introducing Arts   
178   BBC, iPlayer, TV, Truman and Tennessee: An Int...   
183            BBC, iPlayer, TV, Ex-S, Styling the Swan   
187   BBC, iPlayer, TV, Big Book Weekend, A Big Book...   
...                                                 ...   
292     BBC, iPlayer, TV, Dancing Nation, 2. Highlights   
790   BBC, iPlayer, TV, Glow Up: Britains Next Make-...   
1457       BBC, iPlayer, TV, Tonight, Dame Rebecca West   
1517  BBC, iPlayer, TV, John Buchan: Master of Suspense   
1565  BBC, iPlayer, TV, Profile, The World of Philip...   

                                         synopses_small  \
75    A major new production of the classic musical ...   
177   Brenda Emmanus presents short films that combi...   
178   Docudrama that creates a fascinating compariso...   
183   Jasper Conran designs the costumes for Swan La...   
187   Alex Clark talks to the queen of crime Val McD...   
...                                                 ...   
292   Highlights of world-class performances by the ...   
790   The Glow Up final. An industry masterclass and...   
1457  The writer Dame Rebecca West in conversation w...   
1517  Docudrama about the life of author John Buchan...   
1565  Philip Pullman explores Oxford, where he was a...   

                                             synops_med  \
75    Filmed live at the Barbican in London, this ma...   
177   Brenda Emmanus presents short films from emerg...   
178   Docudrama that builds a fascinating picture of...   
183   First transmitted in 1995, Jasper Conran desig...   
187   Alex Clark talks to Val McDermid about t

In [136]:
from datetime import datetime
format = "%Y"
dates = [datetime.strptime(dates[-4:], format) for dates in df_BBC.release_date]

In [149]:
pd.date_range(min(dates), max(dates), freq = "Y").tolist()[0]

Timestamp('1933-12-31 00:00:00', freq='A-DEC')

In [151]:
list(get_recommendations("Planet Earth II", cosine_sim, indices).index)

[312, 338, 382, 360, 311, 358, 410, 294, 418]

In [170]:
cosine_sim[:, ind] += 0.1

In [171]:
cosine_sim[:, ind]

array([[2.03, 2.08, 2.07, ..., 2.07, 2.07, 2.1 ],
       [2.02, 2.03, 2.03, ..., 2.02, 2.03, 2.03],
       [2.02, 2.03, 2.03, ..., 2.02, 2.03, 2.02],
       ...,
       [2.04, 2.09, 2.08, ..., 2.07, 2.09, 2.07],
       [2.02, 2.04, 2.03, ..., 2.02, 2.04, 2.04],
       [2.04, 2.12, 2.1 , ..., 2.09, 2.1 , 2.08]])